version: "3.8"

services:
  frontend:
    container_name: eve-frontend
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Nur das Frontend wird nach außen exposed
    env_file:
      - ./ENV/.env.frontend
    environment:
      - NODE_ENV=production
    networks:
      - eve-network

  backend:
    container_name: eve-backend
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    env_file:
      - ./ENV/.env.backend
    environment:
      - NODE_ENV=production
    volumes:
      - /home/marvin/eve/packages/discord-bot/src/downloads:/app/dist/downloads
    networks:
      - eve-network

  discord-bot:
    container_name: eve-discord-bot
    build:
      context: ./packages/discord-bot
      dockerfile: Dockerfile
    env_file:
      - ./ENV/.env.discord-bot
    environment:
      - NODE_ENV=production
    networks:
      - eve-network

networks:
  eve-network:
    driver: bridge
