name: Deploy to VPS

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Code aus dem Repo auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # SSH-Agent einrichten, damit GitHub Actions deinen privaten SSH-Schlüssel verwenden kann.
      # Der private Schlüssel wird als Secret (z.B. EVE_DEPLOY_KEY) in deinem Repository hinterlegt.
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EVE_DEPLOY_KEY }}

      # Deployment auslösen: Verbindung zum VPS herstellen, ins Repo wechseln, pullen und das Deploy-Skript ausführen. 
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd /home/marvin/eve && ./deploy.sh"
