name: Deploy to VPS

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Code aus dem Repo auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # SSH-Agent einrichten, damit GitHub Actions deinen privaten SSH-Schlüssel verwenden kann.
      # Der private Schlüssel wird als Secret (z.B. VPS_SSH_PRIVATE_KEY) in deinem Repository hinterlegt.
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      # Deployment auslösen: Verbindung zum VPS herstellen, ins Repo wechseln, pullen und das Deploy-Skript ausführen.
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd /pfad/zu/eve && git pull && ./deploy.sh"
